[package]
name = "papagpu"
author = "Michele De Pascalis"
version = "0.1.0"
edition = "2021"

[dependencies]
emu_core = { version = "*", features = ["glsl-compile"] }
futures = "*"
zerocopy = "*"
env_logger = "0.8.4"
